//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.DetailTransactions = new HashSet<DetailTransaction>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int ItemCount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DetailTransaction> DetailTransactions { get; set; }
    }
}
