//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.DetailTransactions = new HashSet<DetailTransaction>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> CouponID { get; set; }
        public double TotalPrice { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<DetailTransaction> DetailTransactions { get; set; }
    }
}
